"""Auto migration

Revision ID: 1c241168c519
Revises: 2f81ffbfa86a
Create Date: 2025-08-13 13:30:30.822187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c241168c519'
down_revision = '2f81ffbfa86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.alter_column('dosage',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.alter_column('dosage',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
