"""Auto migration

Revision ID: 9c0bf0dc1e8e
Revises: 4545e244d121
Create Date: 2025-08-14 11:15:44.916889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0bf0dc1e8e'
down_revision = '4545e244d121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
